### ISSUE TITLE
Do not cancel the search process

### ISSUE THREAD

**Issue by inode64** [Tatsh/livecheck#192]
Now in any ebuild that cannot be updated a raise is generated and this means that you have to exclude the packages that cannot be automatically searched
I have thought about changing the "raise" to "logger.debug" so you can analyze an entire portage without interruptions

What do you think?

**Comment by Tatsh** [comment]
The behaviour changed? I have been only using the last released version for a while so I was unaware.

Definitely would prefer that the failed package get logged at error level but not raise.

**Comment by inode64** [comment]
Tomorrow I'll try to prepare a commit and see if it's correct.
