### ISSUE TITLE
Is use_vercmp necessary?

### ISSUE THREAD

**Issue by inode64** [Tatsh/livecheck#206]
I've been reviewing the code and I see that there is a use_vercmp flag.
What's the point of not using vercmp? because in the end it is important to correctly determine the versions, otherwise the portage can cause problems

**Comment by Tatsh** [comment]
If the version string provided by upstream is something vercmp() can handle then use_vercmp is True.

It won't be true for cases like comparing hashes where the only check there is to see if they are different.
