### ISSUE TITLE
 integration with github repository

### ISSUE THREAD

**Issue by inode64** [Tatsh/livecheck#211]
How do you automatically upload the changes that livecheck generates?

Have you thought about the possibility of a flag to commit, del and add new files?
This way it automatically uploads new ebuilds to github

**Comment by Tatsh** [comment]
It's in scripts in my tatsh-overlay repo. It's very basic and only checks that the prepare stage passes. For 99% of packages that is enough.

**Comment by Tatsh** [comment]
Hold off on this feature please. Or make a separate branch and be prepared to rebase.
